
version: '2'
services:
  zookeeper:
    image: zookeeper
    restart: always
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888

  nifi-ca:
    image:  aldrin/nifi-tls-toolkit:1.1.1
    ports:
      - "18443:8443"
    command: "server -t ${tls_token} -D CN=nifi-ca,OU=Docker NiFi"

  nifi-node:
    build: ./
    ports:
      - "8080-8082"
      - "8443"
    environment:
      tls_token: ${tls_token}
    links:
      - nifi-ca:nifi-ca
    depends_on:
      - zookeeper

  monitor:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.portainer/data:/data
    ports:
      - 9000:9000
