
version: '3'
services:

  nifi-ca:
    image:  aldrin/apache-nifi-tls-toolkit
    hostname: nifi-ca
    ports:
      - "18443:8443"
    command: "server -t ${tls_token} -D CN=nifi-ca,OU=Docker NiFi"

  nifi-node:
    build: ./
    ports:
      - 8080
      - 8081
      - 8082
      - 28443:8443
    environment:
      tls_token: ${tls_token}
      LDAP_AUTHENTICATION_STRATEGY: 'SIMPLE'
      LDAP_MANAGER_DN: 'cn=admin,dc=example,dc=org'
      LDAP_MANAGER_PASSWORD: 'password'

      LDAP_USER_SEARCH_BASE: 'dc=example,dc=org'
      LDAP_USER_SEARCH_FILTER: 'cn={0}'
      LDAP_IDENTITY_STRATEGY: 'USE_DN'

      LDAP_URL: 'ldap://ldap:389'

      # Optional properties only needed for secure STARTTLS or LDAPS
      LDAP_TLS_KEYSTORE: ''
      LDAP_TLS_KEYSTORE_PASSWORD: ''
      LDAP_TLS_KEYSTORE_TYPE: ''
      LDAP_TLS_TRUSTSTORE: ''
      LDAP_TLS_TRUSTSTORE_PASSWORD: ''
      LDAP_TLS_TRUSTSTORE_TYPE: ''
    links:
      - nifi-ca:nifi-ca
  #   depends_on:
  #     - zookeeper

  ldap:
    image: osixia/openldap:1.1.9
    hostname: ldap
    volumes:
      - /Users/apiri/Development/docker-data/ldap/database:/var/lib/ldap # LDAP database
      - /Users/apiri/Development/docker-data/ldap/config:/etc/ldap/slapd.d # LDAP config
      - /Users/apiri/Development/docker-data/ldap/certs:/container/service/slapd/assets/certs # certificates
    ports:
      - 6389:389
      - 6636:636
    environment:
      # Default admin - cn=admin,dc=example,dc=org
      LDAP_ADMIN_PASSWORD: password
      # LDAP_ORGANISATION: Apache NiFi
      # LDAP_DOMAIN: ldap.nifi.apache.org
      # LDAP_TLS_CRT_FILENAME: my-ldap.crt
      # LDAP_TLS_KEY_FILENAME: my-ldap.key
      # LDAP_TLS_CA_CRT_FILENAME: the-ca.crt

  # ldapadmin:
  #   image: osixia/phpldapadmin:0.7.0
  #   ports:
  #     - 6480:80
  #     - 6443:443
  #   environment:
  #     PHPLDAPADMIN_LDAP_HOSTS: ldap

# volumes:
#   ldap-database-volume: /Users/apiri/Development/docker-data/ldap/database
  # ldap-config-volume: /Users/apiri/Development/docker-data/ldap/config
  # ldap-data-volume: /Users/apiri/Development/docker-data/ldap/data
  # ldap-cert-volume: /Users/apiri/Development/docker-data/ldap/certs

  # monitor:
  #   image: portainer/portainer
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ${HOME}/.portainer/data:/data
  #   ports:
  #     - 9000:9000
