
version: '2'
services:
  nifizk:
    image: zookeeper
    restart: always
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=nifizk:2888:3888

  nifi-ca:
    image:  aldrin/apache-nifi-tls-toolkit
    hostname: nifi-ca
    ports:
      - "18443:8443"
    command: "server -t ${tls_token} -D CN=nifi-ca,OU=Docker NiFi"

  nifi-node:
    build: ./
    ports:
      - 8080
      - 8081
      - 8082
      - 8443
    environment:
      tls_token: ${tls_token}
      zookeeper_connect_string: nifizk
    links:
      - nifi-ca:nifi-ca
    depends_on:
      - nifizk

  monitor:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.portainer/data:/data
    ports:
      - 9000:9000
