
version: '2'
services:
  zookeeper:
    image: zookeeper
    restart: always
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888

  nifi-node:
    build: ./
    ports:
      - "8080-8082"
    depends_on:
      - zookeeper
