
version: '2'
services:
  zookeeper:
    image: zookeeper
    restart: always
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888

  nifi-node:
    build: ./
    ports:
      - 8080
      - 8081
      - 8082
      - 8443
        #    environment:
        #tls_token: ${tls_token}
    depends_on:
      - zookeeper
